deploy:
  provider: s3
  access_key_id: AKIAJ6SNC5JHKYFIWB2A
  secret_access_key:
    secure: l9VSTrXj+pnjuD6shjIZFfeq8i+OdjdR8RZIY3WN0Fwdmu6Jp/STNVA6xiUlqDoLs6RfKCLg4scgtwdA4QeSaLQQsTTSOTVHHGc91wWoXZxw3sseHNhPF+8q6FaAN7QGqjOIXL45d2J9vfcTg5XWWF3D/s/hx8RVeaZimoOaaMqZQF7Lo9zEe0sPBIcAjqPsOYQQiDoMhBqkXWFKxeuTe8H1aaE+3tvKzCvBCXTN6YtRkJmh6SGbuIDxvwM4Hyq+Daxp+VxFbHm8exESjEjmrPNHNSkXHt5wKI5IrW1Hb12VOMzu41fu9+cu76XY8ANfTvnk4wxxKyUEiQr6iuAmkXpNXr7iCkZPLlWL6WLyRq5AjRpbCjwcQ3c68SJSHaURKUA3Bsv8ZdnVB66KqCATyNxKM0n82X6WLuddCNCPeLAgx9ntlV1/IJ9+FfSfysT/Z/vnuujiCzUxn62ewnFdr2OC9rtYKgzDElWMF78xPVGOkjc1Le/jqFXmVfS2FW1Rgpt+/8FcHgWvGVmBCb0pFoMay/CRnSyqJJXzUSq0HT++RB9nipLZO9dcez8Nj6mPbjdJw25me+e52NlaaOKLnf+/1SQeQlTLK1nIyAQOEIXQo3ACE1p/nP5Qm2lY5nz/FYFp9G/2ZlliW1pZmuCl7MJjJ2KYj5D5tHQK2wHVOXw=
  bucket: saltandsugar.tech
  local-dir: saltandsugar.tech
  upload-dir: saltandsugar.tech/public
  acl: ''
  on:
    repo: mira-gfx/Hugo-blog
