version: 0.2
env:
  variables:
    LC_CTYPE: "C.UTF-8"
phases:
    install:
        commands:
            - pip install awscli --upgrade --user
            - wget https://github-production-release-asset-2e65be.s3.amazonaws.com/11180687/209bf480-260e-11e9-9abd-f800c1ee24ef?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIAIWNJYAX4CSVEH53A%2F20190324%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20190324T044953Z&X-Amz-Expires=300&X-Amz-Signature=7f36b8a921c170ff59906e3ad215926020cd2a8ea15d87b863bbbe29c6159314&X-Amz-SignedHeaders=host&actor_id=30523995&response-content-disposition=attachment%3B%20filename%3Dhugo_0.54.0_Linux-ARM64.deb&response-content-type=application%2Foctet-stream
            - dpkg -i hugo_${hugo_version}_Linux-64bit.deb
    build:
        commands:
            - hugo
    post_build:
       commands:
            - echo "S3 Upload Beginning"
            - aws s3 sync --delete ./public s3://saltandsugar.tech
            - echo "S3 Upload Complete"