version: 2
jobs:
  build:
    working_directory: ~/saltandsugar.tech
    machine: true
    steps:
      - checkout
      - run:
          name: install hugo
          command: snap install hugo --channel=extended
      - run:
          name: install pygments
          command: pip install pygments
      - run:
          name: build hugo
          pwd: blog/
          command: hugo -t casper
      - save_cache:
          key: blog-{{ epoch }}
          paths:
            - ~/saltandsugar.tech

  approve:
    working_directory: ~/saltandsugar.tech
    machine: true
    steps:
      - run:
          name: noope
          command: echo noope

  deploy:
    working_directory: ~/saltandsugar.tech/public
    machine: true
    steps:
      - restore_cache:
          keys:
            - blog
      - run:
          name: deploy hugo 
          command: aws s3 sync public s3://saltandsugar.tech/

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - approve:
          type: approval
          requires:
            - build
          filters:
            branches:
              only: master
      - deploy:
          requires:
            - approve
          filters:
            branches:
              only: master
