workflows :
version : 2
jobs :
build :
working_directory : ~/project
 docker :
	- image: cibuilds/hugo:latest
steps:
	- checkout
	- run :
	name : build hugo
	command : hugo
	- save_cache:
	key : site-{{ epoch }}
paths:
	- ~/project/public

deploy:
	working_directory : ~/project
	machine : true
	steps :
	- restore_cache:
	keys :
	- site
	- run :
name : deploy hugo
	command : aws s3 sync public s3://saltandsugar.tech/

workflows :
	version : 2
build_and_deploy :
jobs :
	- build
	- deploy :
requires :
	- build
filters :
branches :
only: master