name: HugoBlog

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: true
    - name: Configure AWS
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-1
    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.62.2'
        extended: true
    - name: Build
      run: hugo --minify
    - name: Deploy
      env: 
        S3_UPLOAD_BUCKET: ${{ secrets.S3_UPLOAD_BUCKET }}
      run:
        aws s3 cp ./public s3://$S3_UPLOAD_BUCKET/ --quiet
